### ISSUE TITLE
Example / README aren't up-to-date anymore

### ISSUE THREAD

**Issue by muesli** [andreykaipov/goobs#1]
Looks like the API diverged from the example.

**Comment by andreykaipov** [comment]
Hi! So sorry!

I was in the middle of refactoring some stuff but got sidetracked with work these past two weeks. I honestly didn't think people would be using this yet! 😅 

I'll get this updated asap!

**Comment by andreykaipov** [comment]
Please lemme know if you need any more help! Should note this library is still using v4.5.0 of the protocol so you may find some events are not available.

**Comment by muesli** [comment]
Nice, thanks for updating! I'm planning to use this as a replacement for `go-obs-websocket` in `obs-cli` and `obs-scene-switcher` once it's ready and supporting the latest protocol.

**Comment by andreykaipov** [comment]
Hi @muesli - just wanted to let you know I got this updated to using v4.9.1 of the protocol!

https://github.com/andreykaipov/goobs/releases/tag/v0.5.0

Please lemme know if you have any other comments or concerns!

**Comment by muesli** [comment]
@andreykaipov Fantastic! Will try to integrate this in `obs-cli` & `obs-scene-switcher` and report back!
