### ISSUE TITLE
wss support

### ISSUE THREAD

**Issue by sueboy19** [andreykaipov/goobs#167]
Hi 

See connection inside write ws:

Can support wss: and port custome design. Thanks.

**Comment by andreykaipov** [comment]
Hey thanks for the issue! So I suppose I can parametrize the scheme here:

https://github.com/andreykaipov/goobs/blob/1267b7f47597143743e1d2e847d6be7bc580ccc8/client.go#L188-L189

However the obs-websocket server unfortunately doesn't seem to support WSS (see https://github.com/obsproject/obs-websocket/issues/26).

Their solution is to put the server behind a reverse proxy like ngrok to secure it. They have a guide on their wiki: https://github.com/obsproject/obs-websocket/wiki/SSL-Tunneling.

**Comment by andreykaipov** [comment]
PR #169 added a new `WithScheme` option to specify when creating the client
