### ISSUE TITLE
When should inputs and mediainputs be used?

### ISSUE THREAD

**Issue by Armaly** [andreykaipov/goobs#188]
Is there a difference between inputs and mediainputs? I was able to create a Media Source and set the Local File path using Inputs.CreateInput() and inputs.NewCreateInputParams. 

```
// Creates New Source
Settings := make(map[string]any)
Settings["local_file"] = "C:/testsounds/test123.mp3"
params := inputs.NewCreateInputParams().WithSceneName(GetActiveScene(Client)).WithInputName("NAME").WithInputKind("ffmpeg_source").WithInputSettings(Settings)
resp, err := Client.Inputs.CreateInput(params)
if err != nil {
     slog.Error("Error", "CreateSource", err)
}
```
I'd like to change the Media Source's Local File parameter to a different file path and play that source. What would be the best way to do this?

My attempt so far has been to continue using inputs but it has not worked out for changing the local file path on my created media source. I get a invalid memory address or nil pointer dereference error. What i've attempted:

```
track := make(map[string]any)
track["local_file"] = "C:/testsounds/test.mp3"
track["OBS_MEDIA_STATE_PLAYING"] = "Playing"
name := "sourceName"

resp, err := Client.Inputs.SetInputSettings(&inputs.SetInputSettingsParams{
		InputName: &name,
		InputSettings: track,
	})
if err != nil {
	slog.Error("Error", "SetMediaSourceSettings", err)
}

```
Should I be switching to mediainputs from here or is this possible with regular inputs? Thanks.

**Comment by andreykaipov** [comment]
I think you want the [`TriggerMediaInputAction`](https://github.com/obsproject/obs-websocket/blob/5.5.4/docs/generated/protocol.md#triggermediainputaction) request.

It expects a `mediaAction` param and one of the values part of the `ObsMediaInputAction` enum is `OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PLAY` which sounds like what you're trying to do. I haven't that enum to the library, but you can see it's definition in the upstream protocol.json here:

https://github.com/obsproject/obs-websocket/blob/5.5.4/docs/generated/protocol.json#L536-L595.

Adding it as a top-level type like the other enums would require additional generation statements (see the following snippet), but in the meantime I think you should be able to just pass it as a string.

https://github.com/andreykaipov/goobs/blob/4294a488734309f98429a4e0a0267cf0a4bbcad9/internal/generate/protocol/main.go#L59-L62

> I get a invalid memory address or nil pointer dereference error.

Can you specify where that's happening? Like the stack trace or the line number?

**Comment by Armaly** [comment]
Hi @andreykaipov , no worries thank you for responding. I hope you had a good holiday!

> I think you want the [TriggerMediaInputAction](https://github.com/obsproject/obs-websocket/blob/5.5.4/docs/generated/protocol.md#triggermediainputaction) request.

> Can you specify where that's happening? Like the stack trace or the line number?

UPDATE: It was a mistake on my end. An external package wasn't properly referencing my client. I got it working and it auto plays the file when the source filepath changes. Just double checking, is it expected behavior for a source to auto play the track once a new filepath has been set? Thanks.

**Comment by andreykaipov** [comment]
> Just double checking, is it expected behavior for a source to auto play the track once a new filepath has been set? 

I'd assume so. When I try in OBS manually changing the local file path for a media source, it plays the file automatically first.

And I think this thread details similar behaviour https://obsproject.com/forum/threads/prevent-obs-playing-a-mediasource.176499/ (though I'm not sure what they mean by triggers).

The immediate workaround I can think of is probably just hiding the source until you're ready to play it.

**Comment by Armaly** [comment]
Got it, thanks @andreykaipov!
