### ISSUE TITLE
Please support setting the client name and version

### ISSUE THREAD

**Issue by bdrung** [andreykaipov/goobs#23]
Please allow users of the goobs library to set the client name and version. Otherwise it will use `Go-http-client/1.1`. See also https://github.com/muesli/obs-cli/issues/26

`websocket.Dial` takes a `requestHeader` of type `http.Header` which could be used.

**Comment by andreykaipov** [comment]
I added support in #25 but I'll keep this open till I cut a new release. Thank you for the issue!

Usage for it would be like seen here:

**Comment by andreykaipov** [comment]
Oh weird it auto closed

**Comment by bdrung** [comment]
Thanks.

**Comment by andreykaipov** [comment]
Released in v0.8.0!
