### ISSUE TITLE
timeout waiting for authentication

### ISSUE THREAD

**Issue by alexluecke** [andreykaipov/goobs#36]
Trying to connect to OBS on Windows local network gives authentication error.

### Steps to reproduce:

1. Configure ethernet on windows to be private and open port 4444 (not 4455 from tutorial)
1. Configure OBS 27.2.4 with obs-websockets 4.9.1-compat
1. Follow the "Here's a basic example" tutorial
1. Run program

The OBS log will show connection is established (meaning it is not a firewall issue)

```
11:59:21.137: [obs-websocket 4.9.1-compat] new client connection from 192.168.1.3:38014
11:59:31.146: [obs-websocket 4.9.1-compat] Websocket connection with client '192.168.1.3:38014' closed (disconnected). Code is 1006, reason is: 'End of File'
```

The program exits with:

```
2022/08/14 18:53:19 timeout waiting for authentication: 10000ms
exit status 1
```

I re-entered the OBS websocket password several times to ensure it's not a typo in the password.

**Comment by alexluecke** [comment]
I think this has to do with the v5.0.x auth flows for OBS websockets. Maybe the README should make it more apparent what OBS websocket version you should be using?

**Comment by andreykaipov** [comment]
Oh thanks for catching that! I added a check to error out if we connect to v4.x servers. See https://github.com/andreykaipov/goobs/pull/37.

Should save somebody from the future some debugging time.

The latest release to support v4.x is https://github.com/andreykaipov/goobs/releases/tag/v0.8.1 btw.
