### ISSUE TITLE
Handling reconnects

### ISSUE THREAD

**Issue by GKStretton** [andreykaipov/goobs#48]
Hi, thanks for the software, it's very easy to use! One problem, I was using Client.Conn.SetCloseHandler before to trigger repeated reconnect attempts, but conn is no longer public in client since the v5 upgrade. How do you recommend handling reconnects for a long-running application where obs may open and close multiple times during runtime? I wonder if we could get conn back as a public variable if there's no other good way to do this?

Many thanks

**Comment by afriza** [comment]
My guess is that you listen to errors using [`Client.Listen()`](https://pkg.go.dev/github.com/andreykaipov/goobs#Client.Listen) and then inspect it using type switch ..

**Comment by GKStretton** [comment]
Thanks for the pointers! I couldn't get errors.Is to work, but the following code reliably detects OBS closing. There's also [this example](https://github.com/andreykaipov/goobs/blob/master/examples/sources/main.go) that uses the [ExitStarted](https://pkg.go.dev/github.com/andreykaipov/goobs@v0.12.0/api/events#ExitStarted) event, but I opted for checking for websocket.CloseError to be safe.

```go
func connectionListener() {
	reconnect := make(chan bool)
	for {
		fmt.Printf("Attempting connection to OBS...\n")
		c = nil
		var err error
		c, err = goobs.New(os.Getenv("OBS_URL"))
		for err != nil {
			fmt.Printf("failed to create obs ws client, retrying in %d seconds: %v\n", retryWaitS, err)
			time.Sleep(time.Second * time.Duration(retryWaitS))
			c, err = goobs.New(os.Getenv("OBS_LANDSCAPE_URL"))
		}

		resp, err := c.General.GetVersion()
		if err != nil {
			fmt.Printf("failed to get obs version on connect: %v\n", err)
			continue
		}
		fmt.Printf("Connected to OBS\n"+
			"\tOBSversion: %s\n"+
			"\tOBSws version: %s\n",
			resp.ObsVersion, resp.ObsWebSocketVersion,
		)
		go c.Listen(func(i interface{}) {
			err, ok := i.(error)
			if ok {
				innerErr := errors.Unwrap(err)
				wsErr, ok := innerErr.(*websocket.CloseError)
				if ok {
					fmt.Printf("websocket closed: %v\n", wsErr)
					reconnect <- true
				} else {
					fmt.Printf("misc obs error: %v\n", innerErr)
				}
			}
		})

		<-reconnect
	}
}

```
