### ISSUE TITLE
Can't use library in parallel.

### ISSUE THREAD

**Issue by Vany** [andreykaipov/goobs#55]
i'm using one client from two components of my system.
and recive lot of messages like
```
{"level":"error","error":"request GetStreamStatus: mismatched ID: expected response with ID 670b6c3b-2048-446f-7255-a21cbec8ed58, but got d575668f-54e7-4502-53a6-1ec01e9b371c","message":"Stream.GetStreamStatus() failed"}

and then immediatly :
{"level":"error","error":"request GetRecordStatus: mismatched ID: expected response with ID d575668f-54e7-4502-53a6-1ec01e9b371c, but got 670b6c3b-2048-446f-7255-a21cbec8ed58","message":"obs GetRecordStatus failed"}
```

Seems like something bad in parallel requests.

**Comment by andreykaipov** [comment]
Hi @Vany thanks for your issue. PR https://github.com/andreykaipov/goobs/pull/54 came in the other day and I think would fix the problem. 

I just cut a new release [v0.12.1](https://github.com/andreykaipov/goobs/releases/tag/v0.12.1) containing it if you'd like to try. Please let me know!

**Comment by Vany** [comment]
https://github.com/Vany/controlrake/commit/79e97a2707dd1f1193dc7ccd11f1c7e62cd47335
Seems works.
Lot of thanks!
