### ISSUE TITLE
great jobs! ask whether it can create ,for example,a pic in to live scene,dynamic?

### ISSUE THREAD

**Issue by zsq2010** [andreykaipov/goobs#59]
i would like to change assets showing on the scene or put a new on it
is it possible and how?

**Comment by andreykaipov** [comment]
Hey @zsq2010, apologies for the late reply. You've likely figured it out, but if I understood correctly, for changing what shows up on the scene, you'll first want to find all the scene items with [GetSceneItemList](https://github.com/obsproject/obs-websocket/blob/5.1.0/docs/generated/protocol.md#getsceneitemlist).

And then you have two approaches - setting the scene items indices accordingly so the higher ones show up first with [SetSceneItemIndex](https://github.com/obsproject/obs-websocket/blob/5.1.0/docs/generated/protocol.md#setsceneitemindex), or [SetSceneItemEnabled](https://github.com/obsproject/obs-websocket/blob/5.1.0/docs/generated/protocol.md#setsceneitemenabled) to toggle the visibility of the scene items you want to see versus the ones you don't.

I haven't tested it but based on the available requests, I think that's the most reasonable way to do it.

It might also help to look through the available [scene items events](https://github.com/obsproject/obs-websocket/blob/5.1.0/docs/generated/protocol.md#scene-items-events), and to do what we want in OBS manually, and inspect what events were logged to help us "reverse engineer" a solution.

I added a usage example to the docs that can hopefully act as a "guide" on finding requests that do what a user wants to do at https://github.com/andreykaipov/goobs/tree/main/docs#example.

I'm gonna close this issue but please open up another if you need more help.
